name: Deploy to S3 bucket

# Trigger only for push to master branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to S3 bucket whenever main branch gets new commits
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Run npm install
        run: npm install
      - name: Run npm build
        run: npm run build
      - name: Setup AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run npm deploy
        run: npm run deploy
