name: Deploy to S3 bucket

# Trigger only for push to master branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to S3 bucket whenever main branch gets new commits
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Run npm install
        run: npm install
      - name: Run npm build
        run: npm run build
      - name: Sync with s3 bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'build'
